
services:
  frontend:
    build: ./frontend
    container_name: webapp
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend  

  backend:
    build: ./backend
    container_name: api
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/data:/data
    environment:
      DB_DSN: "dbname=osm_data user=postgres password=postgres host=db port=5432"
    depends_on:
      - db

  db:
    image: postgis/postgis:15-3.4
    container_name: pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: osm_data
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
      - ./backend/data:/data
      

volumes:
  pgdata:

